name: Run Tests with pnpm

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache pnpm
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test:ci

      - name: Upload Test Coverage
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage/
